### PR TITLE
Trinket template updates

### PR DESCRIPTION
**Pull request by eah13**
These probably aren't useful to anyone else, but here's the build process for generating the nunjucks templates we'll use to serve the book.

I pulled in version 6.1.3 for our site and ti should be live soon.

### CODE REVIEW

**Comment by eah13** [comment]
I probably should .gitignore those .hind and .htoc files. Any insight into what they do?  Surprised they aren't generated in y'all's existing build process.

**Comment by ChrisMayfield** [comment]
The .hind and .htoc files are from hevea (see http://hevea.inria.fr/doc/manual041.html). I assume "ind" is used to generate the index, and "toc" is for generating the table of contents. They should be .gitignore'd.

**Comment by ChrisMayfield** [comment]
Where did thinkjava.image.tex come from? If that's an auto-generated file, will you add it to .gitignore too? I'd rather not add any more trinket-specific files to the top level directory. Speaking of which, now that you have a trinket subdirectory (which I like), would it make sense to put a separate Makefile there?

**Comment by eah13** [comment]
@ChrisMayfield almost done with these edits.  Let me know when you've pushed your updates and I'll get this live.

**Pull request merged**
